name: Render and Publish

# Trigger the workflow on push to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R (if using R)
        uses: r-lib/actions/setup-r@v2
        if: contains(hashFiles('**/*.qmd'), 'engine: knitr')
        with:
          r-version: 'release'

      - name: Install R dependencies (if using R)
        if: contains(hashFiles('**/*.qmd'), 'engine: knitr')
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr"))'
          # Add any other R packages your project needs

      - name: Setup Python (if using Python)
        uses: actions/setup-python@v4
        if: contains(hashFiles('**/*.qmd'), 'engine: jupyter')
        with:
          python-version: '3.x'

      - name: Install Python dependencies (if using Python)
        if: contains(hashFiles('**/*.qmd'), 'engine: jupyter')
        run: |
          python -m pip install --upgrade pip
          pip install jupyter matplotlib pandas numpy
          # Add any other Python packages your project needs

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Render Quarto Project
        run: |
          quarto render --to html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2